package ventana;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Veterinario;

/*
 * @author David Bravo
 * @author Solange Soto
 * @author Orlando Mendoza
 * @author Lucianno Valdebenito
 */

//Hereda de JFrame.
public class VentanaLista extends javax.swing.JFrame {

    //Atributos clase tabla
    private DefaultTableModel dfTabla;
    /*
    *Se crean objetos para almacenar los atributos de los veterinarios
    *para luego mostrarlos por la tabla.
    */
    private Object[] o = new Object[8];
    ArrayList<Veterinario> lista;

    public VentanaLista(ArrayList<Veterinario> veterinarios) {
        //Cambiar el icono de la aplicación que se encuentra arriba la izquierda
        setIconImage(new ImageIcon(getClass().getResource("/Vetpeticono.png")).getImage());
        initComponents();
        this.lista = veterinarios;
        dfTabla = new DefaultTableModel();
        dfTabla.addColumn("Nombre");
        dfTabla.addColumn("Edad");
        dfTabla.addColumn("Teléfono");
        dfTabla.addColumn("Rut");
        dfTabla.addColumn("Especialidad");
        dfTabla.addColumn("Dirección");
        dfTabla.addColumn("Precio de consulta");
        dfTabla.addColumn("Correo");
        this.Tabla.setModel(dfTabla);
        /*
        *A partir de la lista enviada desde VentanaVeterinario
        *se procede a guardar cada uno de los datos dentro
        *de la tabla.
        */
        for (int i = 0; i < lista.size(); i++) {
            o[0] = lista.get(i).getNombre();
            o[1] = lista.get(i).getEdad();
            o[2] = lista.get(i).getTelefono();
            o[3] = lista.get(i).getRut();
            o[4] = lista.get(i).getEspecialidad();
            o[5] = lista.get(i).getDireccion();
            o[6] = lista.get(i).getPrecio();
            o[7] = lista.get(i).getCorreo();
            dfTabla.addRow(o);
        }
    }

    public void pagar() {
        int fila = this.Tabla.getSelectedRow();//Obtengo id fila seleccionada
        if (fila >= 0) {
            String precioString = Tabla.getValueAt(fila, 6).toString();
            int precio = Integer.parseInt(precioString);
            int presupuesto = Integer.parseInt(this.PresupuestoTF.getText());
            if (precio <= presupuesto) {
                JOptionPane.showMessageDialog(null, "Cancelado");
            } else {
                JOptionPane.showMessageDialog(null, "Sin presupuesto");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un veterinario para pagar y su presupuesto");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        PagarBtn = new javax.swing.JButton();
        SalirBTN = new javax.swing.JButton();
        PresupuestoLB = new javax.swing.JLabel();
        PresupuestoTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        PagarBtn.setText("Pagar");
        PagarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarBtnActionPerformed(evt);
            }
        });

        SalirBTN.setText("Salir");
        SalirBTN.setToolTipText("");
        SalirBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBTNActionPerformed(evt);
            }
        });

        PresupuestoLB.setText("Presupuesto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PresupuestoLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PresupuestoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PagarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SalirBTN)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PagarBtn)
                    .addComponent(SalirBTN)
                    .addComponent(PresupuestoLB)
                    .addComponent(PresupuestoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PagarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarBtnActionPerformed
        pagar();
    }//GEN-LAST:event_PagarBtnActionPerformed

    private void SalirBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirBTNActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PagarBtn;
    private javax.swing.JLabel PresupuestoLB;
    private javax.swing.JTextField PresupuestoTF;
    private javax.swing.JButton SalirBTN;
    private javax.swing.JTable Tabla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
